### ISSUE TITLE
Fonts have white background

### ISSUE THREAD

**Issue by gingerbeardman** [hunterbridges/PDFontConvert#1]
I noticed the fonts all have white background, which was unexpected and unlike other fonts I've created or those that come with the SDK (which are all on transparent background)

**Comment by hunterbridges** [comment]
I did notice this as well, and have been getting around it using draw modes. I probably just need to make sure the white color is marked as transparent in the image palette data

**Comment by hunterbridges** [comment]
I believe this is fixed in the generator as of https://github.com/hunterbridges/PDFontConvert/commit/2200e03f2bc46656d5b7c859c9cc6dffaf92749b, but I haven't generated the fonts again yet because I'm still working on #2

**Comment by hunterbridges** [comment]
Should be fix as of [8d01fc4](https://github.com/hunterbridges/PDFontConvert/commit/8d01fc4a0374fbd276b94e38925e8c4547e4a6b8), give it a look
