### ISSUE TITLE
Repeated rows of pixels (stretched fonts, not native resolution)

### ISSUE THREAD

**Issue by gingerbeardman** [hunterbridges/PDFontConvert#2]
The following fonts are bad, they have repeated rows
- JF-Dot-Ayu20
- JF-Dot-Izumi16
- JF-Dot-jiskan16s
- ...

At this point I would say they all have the chance of being bad 😢 

## Repro
- loading the .fnt files into tophat web editor
- load the font into a Playdate app/game

## Screenshots

![image](https://user-images.githubusercontent.com/49612/181126549-6b4cc378-6b2b-4afb-96cf-538aee8eca3c.png)

![image](https://user-images.githubusercontent.com/49612/181126769-ea02679c-b5f2-49e8-902c-34e544647964.png)

**Comment by hunterbridges** [comment]
Ah yeah this is a little tricky... it may have to do with [this line](https://github.com/hunterbridges/PDFontConvert/blob/master/font_convert.py#L29), or may be something to do with the otf2bdf utility. Basically, these fonts are provided based on the pixel line height, but otf2bdf accepts the input font size in points. The conversion is supposed to be `pt = px * 0.75`, but there must be some ambiguity or inaccuracy with either the conversion or the ttf metadata. I can take another look

I don't think _all_ the fonts are bad, as I've spot checked some specimens at other sizes and they seem correct. But it may be ones of certain heights. Either way I can dig in to the obviously broken ones and see if there's some way to tweak it to make them correct. Thanks for checking

**Comment by gingerbeardman** [comment]
Given that some are tainted my confidence is low that they are not all tainted (for example look at the second image where only the "s" is bad in that screenshot) and it would be tricky to eyeball all characters of all fonts, so it needs to be fixed at a logic/code/process level.

**Comment by hunterbridges** [comment]
Regardless, I will have to re run them all anyway due to #1. So I will try to figure out the right sizing formula before processing them all again

**Comment by hunterbridges** [comment]
I have made some progress on this... tl;dr, I made a fork of otf2bdf and modified it to let me pass in point sizes in double format, and reversed the point size formula to get the right precision input. But now there's a bug in that patched otf2bdf affecting the bounding box, so glyphs aren't properly aligning to the baseline. I'll mess around a little more with it next chance I get

**Comment by hunterbridges** [comment]
Should be fixed as of [8d01fc4](https://github.com/hunterbridges/PDFontConvert/commit/8d01fc4a0374fbd276b94e38925e8c4547e4a6b8)
